### ISSUE TITLE
installing 1.4 with 4.1.10 deb fails as current version is 4.1.9

### ISSUE THREAD

**Issue by kript** [irods/irods_auth_plugin_kerberos#15] opened 2016-11-11 10:30 UTC
```
dpkg -i irods-auth-plugin-krb-1.4-ubuntu12-x86_64.deb irods-database-plugin-oracle-1.9-ubuntu12-x86_64.deb irods-dev-4.1.10-ubuntu12-x86_64.deb irods-icat-4.1.10-ubuntu12-x86_64.deb 
(Reading database ... 242303 files and directories currently installed.)
Preparing to replace irods-auth-plugin-krb 1.3 (using irods-auth-plugin-krb-1.4-ubuntu12-x86_64.deb) ...
Local iRODS is 4.1.9
This plugin requires iRODS 4.1.10
dpkg: error processing irods-auth-plugin-krb-1.4-ubuntu12-x86_64.deb (--install):
 subprocess new pre-installation script returned error exit status 1
Preparing to replace irods-database-plugin-oracle 1.9 (using irods-database-plugin-oracle-1.9-ubuntu12-x86_64.deb) ...
Unpacking replacement irods-database-plugin-oracle ...
Preparing to replace irods-dev 4.1.9 (using irods-dev-4.1.10-ubuntu12-x86_64.deb) ...
Unpacking replacement irods-dev ...
Preparing to replace irods-icat 4.1.9 (using irods-icat-4.1.10-ubuntu12-x86_64.deb) ...
Upgrading Existing iRODS Installation
Unpacking replacement irods-icat ...
Setting up irods-dev (4.1.10) ...
Setting up irods-icat (4.1.10) ...
 System start/stop links for /etc/init.d/irods already exist.
Configuration Schema Version is already up to date (version=2).
Stopping iRODS server...
Catalog Schema Version is already up to date (version=4).
Starting iRODS server...
Confirming catalog_schema_version... Success
Validating [/usr/local/iRODS/.irods/irods_environment.json]... Success
Validating [/etc/irods/server_config.json]... Success
Validating [/etc/irods/hosts_config.json]... Success
Validating [/etc/irods/host_access_control_config.json]... Success
Validating [/etc/irods/database_config.json]... Success
Processing triggers for ureadahead ...
Processing triggers for man-db ...
Setting up irods-database-plugin-oracle (1.9) ...
Errors were encountered while processing:
 irods-auth-plugin-krb-1.4-ubuntu12-x86_64.deb
```
re-running the installation of just the plugin works fine, but it looks like the version check is done in slightly the wrong place. Prior installation was 4.1.9-preview6.

**Comment by trel** [comment] 2016-11-11 13:44
The preinstall check in the plugins are just to prevent a mismatch in functionality until the interfaces settled down.

It looks like you tried to install the krb plugin before updating the icat package - and the krb preinstall fails as expected.

I think it's working as designed - but please share more information if you still feel something should have worked differently.

**Comment by kript** [comment] 2017-02-13 11:19
Just encountered this again upgrading production. 

My opinion is that this breaks the principle of least surprise given that the packages that are being upgraded *at the same time* are 4.1.10 - I confess to be unclear about how the package management system manages all of this, but if you are installing a package requiring a version that is being upgraded to, it should let you continue. Or at least, if this is the case, the same behavior should exist for e.g. the dev or runtime packages, which presumably have the same requirements (but expressed differently perhaps)?

**Comment by kript** [comment] 2018-01-05 09:46
This behavior continues with 1.5/4.1.11, in that when trying to do;

```
dpkg -i irods-icat-4.1.11-ubuntu12-x86_64.deb irods-dev-4.1.11-ubuntu12-x86_64.deb irods-database-plugin-oracle-1.11-ubuntu12-x86_64.deb irods-auth-plugin-krb-1.5-ubuntu12-x86_64.deb
```

one gets
```

(Reading database ... 74619 files and directories currently installed.)
Preparing to replace irods-icat 4.1.10 (using irods-icat-4.1.11-ubuntu12-x86_64.deb) ...
dpkg: error processing irods-icat-4.1.11-ubuntu12-x86_64.deb (--install):
 subprocess new pre-installation script returned error exit status 1
 System start/stop links for /etc/init.d/irods already exist.

=======================================================================

Welcome to iRODS.

This installation of an iCAT server is currently incomplete and
needs a database plugin to be installed and configured before
it can be started and used.

Please consult the documentation for further instructions.

=======================================================================


Preparing to replace irods-dev 4.1.10 (using irods-dev-4.1.11-ubuntu12-x86_64.deb) ...
Unpacking replacement irods-dev ...
Preparing to replace irods-database-plugin-oracle 1.10 (using irods-database-plugin-oracle-1.11-ubuntu12-x86_64.deb) ...
Unpacking replacement irods-database-plugin-oracle ...
Preparing to replace irods-auth-plugin-krb 1.4 (using irods-auth-plugin-krb-1.5-ubuntu12-x86_64.deb) ...
Local iRODS is 4.1.10
This plugin requires iRODS 4.1.11
dpkg: error processing irods-auth-plugin-krb-1.5-ubuntu12-x86_64.deb (--install):
 subprocess new pre-installation script returned error exit status 1
Setting up irods-dev (4.1.11) ...
Setting up irods-database-plugin-oracle (1.11) ...
Errors were encountered while processing:
 irods-icat-4.1.11-ubuntu12-x86_64.deb
 irods-auth-plugin-krb-1.5-ubuntu12-x86_64.deb
```
and so the entire installation fails

Attempting to then just install `irods-icat-4.1.11-ubuntu12-x86_64.deb irods-dev-4.1.11-ubuntu12-x86_64.deb irods-database-plugin-oracle-1.11-ubuntu12-x86_64.deb` gives you failures on the icat package, since its already installed;

```
ubuntu@irods-41X-test:/irods_4.1.11$ sudo dpkg -i irods-icat-4.1.11-ubuntu12-x86_64.deb irods-dev-4.1.11-ubuntu12-x86_64.deb irods-database-plugin-oracle-1.11-ubuntu12-x86_64.deb  
(Reading database ... 74619 files and directories currently installed.)
Preparing to replace irods-icat 4.1.10 (using irods-icat-4.1.11-ubuntu12-x86_64.deb) ...
dpkg: error processing irods-icat-4.1.11-ubuntu12-x86_64.deb (--install):
 subprocess new pre-installation script returned error exit status 1
 System start/stop links for /etc/init.d/irods already exist.

=======================================================================

Welcome to iRODS.

This installation of an iCAT server is currently incomplete and
needs a database plugin to be installed and configured before
it can be started and used.

Please consult the documentation for further instructions.

=======================================================================


Preparing to replace irods-dev 4.1.11 (using irods-dev-4.1.11-ubuntu12-x86_64.deb) ...
Unpacking replacement irods-dev ...
Preparing to replace irods-database-plugin-oracle 1.11 (using irods-database-plugin-oracle-1.11-ubuntu12-x86_64.deb) ...
Unpacking replacement irods-database-plugin-oracle ...
Setting up irods-dev (4.1.11) ...
Setting up irods-database-plugin-oracle (1.11) ...
Errors were encountered while processing:
 irods-icat-4.1.11-ubuntu12-x86_64.deb
```

So now the only way to proceed is to start hacking preinstall scripts. Possibly one can remove the kerberos package and then force the install then install the plugin but thats unpleasant, although not as unpleasant as hacking preinstall scripts.

This is not the way package versioning is supposed to work, IMHO.

The problem appears to be in the preinstall section of  ` packaging/irods_auth_plugin_krb.list.template` where -REQUIRED_VERSION="4.1.10" is specified and calculated outside of the package management system. 

For Debian, for example, the Debian documentation regarding this is; https://www.debian.org/doc/debian-policy/#document-ch-relationships (you probably want the Pre-Depends set to 4.1.10 for e.g.), but I'm sure there is something similar for Red Hat.

Can we have the package decencies managed b the package management system, whether RPM, APT or something else, please?

**Comment by trel** [comment] 2018-07-19 16:47
I'm willing to loosen/remove this check for the remainder of the 4-1-series.

The packaging has been migrated to CMake and CPack for 4.2+ and should no longer exhibit this limitation.

**Comment by trel** [comment] 2018-11-07 17:58
4.1.12 is out - and it will be the final release against the 4.1 branch.

Closing.

**Closed by trel** 2018-11-07 17:58 UTC
